import Head from 'next/head'
import Hero from '../../components/Hero'
import { use } from 'react'
import { useRouter } from 'next/router';
export async function fetchData() {
    const res = await fetch('https://official-joke-api.appspot.com/random_ten', { cache: "no-store" })
    if (res.ok) {
        return res?.json()
    }
}
const Home = () => {
    const router = useRouter()
    const name = router.query.edituser
    const data = fetchData()
    console.log(data)
    return (
        <main>
            <Head>
                <title>NextJS App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero heading='Edit User' message='I capture moments in nature and keep them alive.' name={name} />
            <h1>Here are some Jokes!</h1>
            <ul >
                {data?.result?.map(joke => (
                    <>
                        <li key={joke.id}>{joke.setup} <br/> {joke.punchline}</li>
                        <br />
                    </>
                ))}
            </ul>
        </main>
    )
}

export default Home