import Head from 'next/head'
import Image from 'next/image'
import HeroEdit from '../../components/HeroEdit'
import Slider from '../../components/Slider'
import { SliderData } from '../../components/SliderData'
export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroEdit heading='Profile' message='I capture moments in nature and keep them alive.' />
      <Slider slides={SliderData} />
    </div>
  )
}
